import { EntitlementOverrideState, FeatureKey, OrganizationStatus, SubscriptionStatus } from '@prisma/client';
import { EntitlementService } from '../src/entitlements/entitlement.service';
const tenant = { organizationId: 'org-a', tenantId: 'org-a', userId: 'user-a', membershipId: 'member-a', tenantRole: 'REP', permissions: [], platformAdmin: false, membershipStatus: 'active' as const, resolutionSource: 'token-session' as const };
const now = new Date('2026-08-13T00:00:00.000Z');
function setup(subscription: any, override: any = null, status: OrganizationStatus = OrganizationStatus.ACTIVE, historyCount = subscription ? 1 : 0) { const prisma: any = { organization: { findUnique: jest.fn().mockResolvedValue({ status, entitlementVersion: Math.random() }) }, subscription: { findFirst: jest.fn().mockResolvedValue(subscription), count: jest.fn().mockResolvedValue(historyCount) }, organizationEntitlement: { findUnique: jest.fn().mockResolvedValue(override) } }; return { prisma, service: new EntitlementService(prisma) }; }
function active(enabled = true, extra: any = {}) { return { id: 'sub-a', status: SubscriptionStatus.ACTIVE, startAt: new Date('2026-08-01'), endAt: new Date('2026-08-20'), gracePeriodEndAt: new Date('2026-08-25'), plan: { code: 'BUSINESS', isActive: true, features: [{ enabled }] }, ...extra }; }
describe('EntitlementService fix 000092', () => {
  it('allows a Plan-enabled Feature', async () => expect(await setup(active()).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: true, source: 'PLAN' }));
  it('denies a Plan-disabled Feature', async () => expect(await setup(active(false)).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: false }));
  it('applies force-disabled and force-enabled overrides', async () => { expect(await setup(active(true), { state: EntitlementOverrideState.DISABLED }).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: false, source: 'OVERRIDE' }); expect(await setup(active(false), { state: EntitlementOverrideState.ENABLED }).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: true, source: 'OVERRIDE' }); });
  it('keeps baseline during bounded grace and denies after grace', async () => { expect(await setup(active(true)).service.resolveForTenant(tenant, FeatureKey.SSO, new Date('2026-08-22'))).toMatchObject({ enabled: true, source: 'GRACE' }); expect(await setup(active(true)).service.resolveForTenant(tenant, FeatureKey.SSO, new Date('2026-08-26'))).toMatchObject({ enabled: false }); });
  it('does not let a cached result cross an exact term or grace boundary', async () => { const { service } = setup(active(true)); expect((await service.resolveForTenant(tenant, FeatureKey.SSO, new Date('2026-08-19T23:59:59Z'))).source).toBe('PLAN'); expect((await service.resolveForTenant(tenant, FeatureKey.SSO, new Date('2026-08-20T00:00:00Z'))).source).toBe('GRACE'); expect((await service.resolveForTenant(tenant, FeatureKey.SSO, new Date('2026-08-25T00:00:00Z'))).enabled).toBe(false); });
  it.each([SubscriptionStatus.PENDING, SubscriptionStatus.SUSPENDED, SubscriptionStatus.CANCELLED, SubscriptionStatus.EXPIRED])('denies %s subscriptions', async (subscriptionStatus) => expect(await setup(active(true, { status: subscriptionStatus })).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: false }));
  it.each([OrganizationStatus.ARCHIVED, OrganizationStatus.SUSPENDED, OrganizationStatus.PENDING_SETUP])('denies lifecycle state %s', async (organizationStatus) => expect(await setup(active(), null, organizationStatus).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: false }));
  it('preserves known Features only for a legacy Organization with no subscription', async () => expect(await setup(null).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: true, source: 'LEGACY_COMPATIBILITY' }));
  it('does not restore compatibility after subscription history exists', async () => expect(await setup(null, null, OrganizationStatus.ACTIVE, 1).service.resolveForTenant(tenant, FeatureKey.SSO, now)).toMatchObject({ enabled: false, source: 'DENIED' }));
  it('fails closed for an unknown Feature', async () => expect(await setup(null).service.resolve('org-a', 'UNKNOWN' as FeatureKey, now)).toMatchObject({ enabled: false, source: 'DENIED' }));
  it('always queries using the trusted tenant Organization', async () => { const { prisma, service } = setup(active()); await service.resolveForTenant(tenant, FeatureKey.REPORTING, now); expect(prisma.subscription.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ organizationId: 'org-a' }) })); });
});
