import { SubscriptionStatus, SubscriptionType } from '@prisma/client';
import { PlatformEntitlementsService } from '../src/entitlements/platform-entitlements.service';
const platform = { userId: 'platform-a', platformAdmin: true as const, platformRole: 'PLATFORM_ADMIN' as const };
describe('PlatformEntitlementsService fix 000092', () => {
  it('creates subscription under lock with version and audit in one transaction', async () => { const tx: any = { $queryRaw: jest.fn(), organization: { findUnique: jest.fn().mockResolvedValue({ id: 'org-a' }), update: jest.fn() }, plan: { findFirst: jest.fn().mockResolvedValue({ id: 'plan-a' }) }, subscription: { findFirst: jest.fn().mockResolvedValue(null), create: jest.fn().mockResolvedValue({ id: 'sub-a', organizationId: 'org-a', planId: 'plan-a', type: SubscriptionType.TRIAL, status: SubscriptionStatus.ACTIVE, startAt: new Date(), internalNote: 'private' }) }, auditLog: { create: jest.fn() } }; const service = new PlatformEntitlementsService({ $transaction: (cb: any) => cb(tx) } as any); const result: any = await service.createSubscription('org-a', { planId: 'plan-a', type: SubscriptionType.TRIAL, status: SubscriptionStatus.ACTIVE, startAt: '2026-08-13T00:00:00Z', endAt: '2026-08-20T00:00:00Z' }, platform); expect(tx.$queryRaw).toHaveBeenCalled(); expect(tx.organization.update).toHaveBeenCalledWith(expect.objectContaining({ data: { entitlementVersion: { increment: 1 } } })); expect(tx.auditLog.create).toHaveBeenCalled(); expect(result.internalNote).toBeUndefined(); });
  it('rejects overlapping current subscriptions', async () => { const tx: any = { $queryRaw: jest.fn(), organization: { findUnique: jest.fn().mockResolvedValue({ id: 'org-a' }) }, plan: { findFirst: jest.fn().mockResolvedValue({ id: 'plan-a' }) }, subscription: { findFirst: jest.fn().mockResolvedValue({ id: 'existing' }) } }; const service = new PlatformEntitlementsService({ $transaction: (cb: any) => cb(tx) } as any); await expect(service.createSubscription('org-a', { planId: 'plan-a', type: SubscriptionType.STANDARD, startAt: '2026-08-13T00:00:00Z' }, platform)).rejects.toThrow('already has a current subscription'); });
  it('rejects invalid dates before database mutation', async () => { const service = new PlatformEntitlementsService({} as any); await expect(service.createSubscription('org-a', { planId: 'plan-a', type: SubscriptionType.TRIAL, startAt: '2026-08-14T00:00:00Z', endAt: '2026-08-13T00:00:00Z' }, platform)).rejects.toThrow('endAt must be after startAt'); });
  it('rejects invalid initial lifecycle states', async () => { const service = new PlatformEntitlementsService({} as any); await expect(service.createSubscription('org-a', { planId: 'plan-a', type: SubscriptionType.STANDARD, status: SubscriptionStatus.SUSPENDED, startAt: '2026-08-13T00:00:00Z' }, platform)).rejects.toThrow('must start PENDING or ACTIVE'); });
  it('rejects invalid terminal-state transition', async () => { const tx: any = { subscription: { findUnique: jest.fn().mockResolvedValue({ id: 'sub-a', organizationId: 'org-a', status: SubscriptionStatus.EXPIRED }) }, $queryRaw: jest.fn() }; const service = new PlatformEntitlementsService({ $transaction: (cb: any) => cb(tx) } as any); await expect(service.transition('sub-a', { status: SubscriptionStatus.ACTIVE }, platform)).rejects.toThrow('Invalid subscription transition'); });
});
