import { BadRequestException, ConflictException, ForbiddenException } from '@nestjs/common';
import { Priority, TaskAssignmentScope, TaskReviewDecision, TaskReviewStatus, TaskStatus, UserRole } from '@prisma/client';
import { TasksService } from '../src/tasks/tasks.service';
import { tenantUser } from './helpers/tenant-user';
import type { CurrentUserPayload } from '../src/common/decorators/current-user.decorator';

const organizationId = '00000000-0000-4000-8000-000000000001';
function actor(userId: string, permissions: string[]) { const value = tenantUser<CurrentUserPayload>({ userId, email: `${userId}@test.local`, role: UserRole.REP, organizationId }); return { ...value, tenantContext: { ...value.tenantContext!, permissions } }; }
const submitter = actor('00000000-0000-4000-8000-000000000011', ['task:view', 'task:submit-review', 'task:complete']);
const reviewer = actor('00000000-0000-4000-8000-000000000012', ['task:view', 'task:review']);
function task(overrides: Record<string, unknown> = {}) { return { id: '00000000-0000-4000-8000-000000000021', organizationId, title: 'Security review', description: null, status: TaskStatus.IN_PROGRESS, priority: Priority.HIGH, assignmentScope: TaskAssignmentScope.SELF, teamId: null, parentTaskId: null, companyId: null, personId: null, opportunityId: null, commercialDocumentId: null, paymentId: null, meetingId: null, activityId: null, productId: null, assignedToId: submitter.userId, createdById: submitter.userId, requiresReview: true, reviewStatus: TaskReviewStatus.DRAFT, reviewerId: reviewer.userId, reviewRounds: [], reviewer: { id: reviewer.userId }, subtasks: [], _count: { subtasks: 0, reviewRounds: 0 }, ...overrides }; }
function setup(overrides: Record<string, unknown> = {}) {
  const current = task(overrides);
  const round = { id: 'round-1', taskId: current.id, organizationId, roundNumber: 1, reviewerId: reviewer.userId, submittedById: submitter.userId, decision: TaskReviewDecision.PENDING };
  const prisma: any = {
    task: { findFirst: jest.fn().mockResolvedValue(current), count: jest.fn().mockResolvedValue(0), update: jest.fn().mockResolvedValue(current), updateMany: jest.fn().mockResolvedValue({ count: 1 }) },
    taskReviewRound: { aggregate: jest.fn().mockResolvedValue({ _max: { roundNumber: 0 } }), create: jest.fn().mockResolvedValue(round), findFirst: jest.fn().mockResolvedValue(round), findMany: jest.fn().mockResolvedValue([round]), updateMany: jest.fn().mockResolvedValue({ count: 1 }) },
    fileAttachment: { count: jest.fn().mockResolvedValue(0) },
    user: { findFirst: jest.fn().mockResolvedValue({ id: reviewer.userId, role: UserRole.REP, isActive: true, organizationMemberships: [{ isTenantOwner: false, role: { permissions: [{ permission: { action: 'task:review', isActive: true } }] } }] }) },
    rolePermission: { count: jest.fn().mockResolvedValue(0) },
  };
  prisma.$transaction = jest.fn((callback: any) => typeof callback === 'function' ? callback(prisma) : Promise.all(callback));
  const audit = { record: jest.fn() }, notifications = { notifyUser: jest.fn() };
  return { service: new TasksService(prisma, audit as any, notifications as any), prisma, audit, notifications, current, round };
}

describe('Phase 4.6 task review workflow', () => {
  it('submits a review round atomically and notifies/audits', async () => { const { service, prisma, audit, notifications, current } = setup(); await service.submitReview(current.id, { note: 'Ready' }, submitter); expect(prisma.taskReviewRound.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ roundNumber: 1, reviewerId: reviewer.userId }) })); expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({ action: 'task.review_submitted' })); expect(notifications.notifyUser).toHaveBeenCalled(); });
  it('blocks duplicate pending submission', async () => { const { service, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); await expect(service.submitReview(current.id, {}, submitter)).rejects.toBeInstanceOf(ConflictException); });
  it('rejects self review', async () => { const { service, current } = setup({ reviewerId: submitter.userId }); await expect(service.submitReview(current.id, {}, submitter)).rejects.toMatchObject({ response: expect.objectContaining({ code: 'TASK_SELF_REVIEW_NOT_ALLOWED' }) }); });
  it('rejects cross-organization or inactive reviewer', async () => { const { service, prisma, current } = setup(); prisma.user.findFirst.mockResolvedValue(null); await expect(service.submitReview(current.id, {}, submitter)).rejects.toMatchObject({ response: expect.objectContaining({ code: 'TASK_REVIEWER_INVALID' }) }); });
  it('validates task-linked tenant artifacts', async () => { const { service, prisma, current } = setup(); prisma.fileAttachment.count.mockResolvedValue(0); await expect(service.submitReview(current.id, { artifactIds: ['00000000-0000-4000-8000-000000000099'] }, submitter)).rejects.toMatchObject({ response: expect.objectContaining({ code: 'TASK_REVIEW_ARTIFACT_INVALID' }) }); });
  it('approves only by assigned reviewer', async () => { const { service, prisma, audit, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); await service.decideReview(current.id, 'APPROVED', { comment: 'OK' }, reviewer); expect(prisma.taskReviewRound.updateMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ decision: TaskReviewDecision.APPROVED }) })); expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({ action: 'task.review_approved' })); });
  it('rejects a non-reviewer decision', async () => { const { service, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); await expect(service.decideReview(current.id, 'APPROVED', {}, submitter)).rejects.toBeInstanceOf(ForbiddenException); });
  it('requires feedback when requesting changes', async () => { const { service, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); await expect(service.decideReview(current.id, 'CHANGES_REQUESTED', {}, reviewer)).rejects.toMatchObject({ response: expect.objectContaining({ code: 'TASK_REVIEW_COMMENT_REQUIRED' }) }); });
  it('records requested changes with reviewer feedback', async () => { const { service, prisma, audit, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); await service.decideReview(current.id, 'CHANGES_REQUESTED', { comment: 'Update assumptions' }, reviewer); expect(prisma.taskReviewRound.updateMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ decision: TaskReviewDecision.CHANGES_REQUESTED, reviewComment: 'Update assumptions' }) })); expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({ action: 'task.review_changes_requested' })); });
  it('creates round two without changing round one', async () => { const { service, prisma, audit, current } = setup({ reviewStatus: TaskReviewStatus.CHANGES_REQUESTED }); prisma.taskReviewRound.aggregate.mockResolvedValue({ _max: { roundNumber: 1 } }); prisma.taskReviewRound.create.mockImplementation(({ data }: any) => Promise.resolve({ id: 'round-2', ...data })); await service.submitReview(current.id, {}, submitter); expect(prisma.taskReviewRound.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ roundNumber: 2 }) })); expect(prisma.taskReviewRound.updateMany).not.toHaveBeenCalled(); expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({ action: 'task.review_resubmitted' })); });
  it('blocks completion before approval and allows it after approval', async () => { const blocked = setup(); await expect(blocked.service.complete(blocked.current.id, {}, submitter)).rejects.toMatchObject({ response: expect.objectContaining({ code: 'TASK_REVIEW_NOT_APPROVED' }) }); const allowed = setup({ reviewStatus: TaskReviewStatus.APPROVED }); await expect(allowed.service.complete(allowed.current.id, {}, submitter)).resolves.toBeDefined(); });
  it('blocks review actions on cancelled tasks', async () => { const { service, current } = setup({ status: TaskStatus.CANCELLED }); await expect(service.submitReview(current.id, {}, submitter)).rejects.toBeInstanceOf(BadRequestException); });
  it('atomically closes a pending review when its task is cancelled', async () => { const { service, prisma, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); await service.changeStatus(current.id, { status: TaskStatus.CANCELLED, note: 'No longer needed' }, submitter); expect(prisma.$transaction).toHaveBeenCalled(); expect(prisma.taskReviewRound.updateMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ decision: TaskReviewDecision.CANCELLED }) })); });
  it('detects a concurrent review decision', async () => { const { service, prisma, current } = setup({ reviewStatus: TaskReviewStatus.PENDING_REVIEW }); prisma.taskReviewRound.updateMany.mockResolvedValue({ count: 0 }); await expect(service.decideReview(current.id, 'APPROVED', {}, reviewer)).rejects.toBeInstanceOf(ConflictException); });
});
