CREATE TYPE "MeetingStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELLED');
CREATE TYPE "MeetingMode" AS ENUM ('IN_PERSON', 'ONLINE', 'HYBRID');
ALTER TYPE "NotificationType" ADD VALUE 'MEETING_REMINDER';
ALTER TYPE "NotificationEntityType" ADD VALUE 'MEETING';
CREATE TABLE "meetings" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"companyId" TEXT NOT NULL,"opportunityId" TEXT,"title" TEXT NOT NULL,"agenda" TEXT,"description" TEXT,"mode" "MeetingMode" NOT NULL,"location" TEXT,"meetingUrl" TEXT,"startAt" TIMESTAMP(3) NOT NULL,"endAt" TIMESTAMP(3) NOT NULL,"reminderAt" TIMESTAMP(3),"reminderSentAt" TIMESTAMP(3),"status" "MeetingStatus" NOT NULL DEFAULT 'SCHEDULED',"organizerId" TEXT NOT NULL,"createdById" TEXT NOT NULL,"completedAt" TIMESTAMP(3),"completedById" TEXT,"completionNote" TEXT,"cancelledAt" TIMESTAMP(3),"cancelledById" TEXT,"cancellationReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "meetings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "meeting_assignees" ("meetingId" TEXT NOT NULL,"userId" TEXT NOT NULL,"assignedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "meeting_assignees_pkey" PRIMARY KEY ("meetingId","userId"));
CREATE TABLE "meeting_attendees" ("meetingId" TEXT NOT NULL,"personId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "meeting_attendees_pkey" PRIMARY KEY ("meetingId","personId"));
CREATE INDEX "meetings_organizationId_startAt_idx" ON "meetings"("organizationId","startAt");
CREATE INDEX "meetings_companyId_startAt_idx" ON "meetings"("companyId","startAt");
CREATE INDEX "meetings_opportunityId_startAt_idx" ON "meetings"("opportunityId","startAt");
CREATE INDEX "meetings_organizerId_startAt_idx" ON "meetings"("organizerId","startAt");
CREATE INDEX "meetings_status_startAt_idx" ON "meetings"("status","startAt");
CREATE INDEX "meetings_reminderAt_reminderSentAt_status_idx" ON "meetings"("reminderAt","reminderSentAt","status");
CREATE INDEX "meeting_assignees_userId_idx" ON "meeting_assignees"("userId");
CREATE INDEX "meeting_attendees_personId_idx" ON "meeting_attendees"("personId");
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "opportunities"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_organizerId_fkey" FOREIGN KEY ("organizerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_completedById_fkey" FOREIGN KEY ("completedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "meeting_assignees" ADD CONSTRAINT "meeting_assignees_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_assignees" ADD CONSTRAINT "meeting_assignees_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_assignees" ADD CONSTRAINT "meeting_assignees_assignedById_fkey" FOREIGN KEY ("assignedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "meeting_attendees" ADD CONSTRAINT "meeting_attendees_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_attendees" ADD CONSTRAINT "meeting_attendees_personId_fkey" FOREIGN KEY ("personId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE;
