import {
  DataQualitySeverity as S,
  ReportingScope as Scope,
} from "./dto/data-quality.dto";
export interface DataQualityRule {
  ruleKey: string;
  entityType: string;
  scope: Scope;
  severity: S;
  title: string;
  description: string;
  fieldNames: string[];
}
const rule = (
  ruleKey: string,
  entityType: string,
  scope: Scope,
  severity: S,
  fieldNames: string[],
  title: string,
): DataQualityRule => ({
  ruleKey,
  entityType,
  scope,
  severity,
  title,
  description: title,
  fieldNames,
});
export const DATA_QUALITY_RULES: DataQualityRule[] = [
  rule(
    "COMPANY_MISSING_OWNER",
    "COMPANY",
    Scope.ORGANIZATION,
    S.HIGH,
    ["ownerId"],
    "Company owner is missing",
  ),
  rule(
    "COMPANY_MISSING_INDUSTRY",
    "COMPANY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["industryId", "industry"],
    "Company industry is missing",
  ),
  rule(
    "COMPANY_MISSING_SOURCE",
    "COMPANY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["sourceId", "source"],
    "Company source is missing",
  ),
  rule(
    "COMPANY_MISSING_PRIMARY_CONTACT",
    "COMPANY",
    Scope.ORGANIZATION,
    S.HIGH,
    ["people.isPrimaryContact"],
    "Primary contact is missing",
  ),
  rule(
    "COMPANY_MISSING_CONTACT_CHANNEL",
    "COMPANY",
    Scope.ORGANIZATION,
    S.HIGH,
    ["publicEmail", "centralPhone", "people.email", "people.phone"],
    "Contact channel is missing",
  ),
  rule(
    "COMPANY_MISSING_NATIONAL_ID",
    "COMPANY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["nationalId"],
    "National ID is missing",
  ),
  rule(
    "OPPORTUNITY_MISSING_OWNER",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.HIGH,
    ["ownerId"],
    "Opportunity owner is missing",
  ),
  rule(
    "OPPORTUNITY_MISSING_ESTIMATED_VALUE",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.HIGH,
    ["estimatedValue"],
    "Estimated value is missing",
  ),
  rule(
    "OPPORTUNITY_MISSING_PROBABILITY",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["probability"],
    "Probability is missing",
  ),
  rule(
    "OPPORTUNITY_MISSING_EXPECTED_CLOSE_DATE",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["expectedCloseDate"],
    "Expected close date is missing",
  ),
  rule(
    "OPPORTUNITY_MISSING_PRIMARY_CONTACT",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["primaryContactId"],
    "Primary contact is missing",
  ),
  rule(
    "OPPORTUNITY_WITHOUT_LINE_ITEMS",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.LOW,
    ["lineItems"],
    "Opportunity has no line items",
  ),
  rule(
    "OPPORTUNITY_CURRENT_STAGE_HISTORY_MISSING",
    "OPPORTUNITY",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["stageHistories"],
    "Current stage history is missing",
  ),
  rule(
    "OPEN_TASK_MISSING_ASSIGNEE",
    "TASK",
    Scope.ORGANIZATION,
    S.HIGH,
    ["assignedToId"],
    "Open task assignee is missing",
  ),
  rule(
    "OPEN_TASK_MISSING_DUE_DATE",
    "TASK",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["dueAt"],
    "Open task due date is missing",
  ),
  rule(
    "PAST_SCHEDULED_MEETING",
    "MEETING",
    Scope.ORGANIZATION,
    S.HIGH,
    ["status", "endAt"],
    "Scheduled meeting is in the past",
  ),
  rule(
    "PAID_PAYMENT_MISSING_PAID_AT",
    "PAYMENT",
    Scope.ORGANIZATION,
    S.HIGH,
    ["status", "paidAt"],
    "Paid payment timestamp is missing",
  ),
  rule(
    "UNPAID_PAYMENT_HAS_PAID_AT",
    "PAYMENT",
    Scope.ORGANIZATION,
    S.HIGH,
    ["status", "paidAt"],
    "Unpaid payment has a paid timestamp",
  ),
  rule(
    "OPEN_PAYMENT_MISSING_DUE_DATE",
    "PAYMENT",
    Scope.ORGANIZATION,
    S.MEDIUM,
    ["status", "dueDate"],
    "Open payment due date is missing",
  ),
  rule(
    "FINAL_DOCUMENT_MISSING_AMOUNT",
    "COMMERCIAL_DOCUMENT",
    Scope.ORGANIZATION,
    S.HIGH,
    ["status", "amount"],
    "Final commercial document amount is missing",
  ),
  rule(
    "ACTIVE_PRODUCT_NON_POSITIVE_IN_PERSON_PRICE",
    "PRODUCT",
    Scope.GLOBAL_CATALOG,
    S.CRITICAL,
    ["inPersonPriceIrr"],
    "In-person price is not positive",
  ),
  rule(
    "ACTIVE_PRODUCT_NON_POSITIVE_DIGIKALA_PRICE",
    "PRODUCT",
    Scope.GLOBAL_CATALOG,
    S.CRITICAL,
    ["digikalaPriceIrr"],
    "Digikala price is not positive",
  ),
  rule(
    "USD_PRODUCT_STALE_EXCHANGE_RATE",
    "PRODUCT",
    Scope.GLOBAL_CATALOG,
    S.HIGH,
    ["calculatedExchangeRateId"],
    "USD product exchange rate is stale",
  ),
  rule(
    "PRODUCT_MISSING_CATEGORY",
    "PRODUCT",
    Scope.GLOBAL_CATALOG,
    S.LOW,
    ["category"],
    "Product category is missing",
  ),
];
export const DATA_QUALITY_RULE_MAP = new Map(
  DATA_QUALITY_RULES.map((rule) => [rule.ruleKey, rule]),
);
