UPDATE "pipeline_stages"
SET
  "isTerminal" = CASE WHEN "code" IN ('DONE', 'ON_HOLD', 'LOST', 'NO_RESPONSE') THEN true ELSE false END,
  "terminalType" = CASE
    WHEN "code" = 'DONE' THEN 'WON'
    WHEN "code" IN ('LOST', 'NO_RESPONSE') THEN 'LOST'
    WHEN "code" = 'ON_HOLD' THEN 'ON_HOLD'
    ELSE 'NONE'
  END,
  "color" = COALESCE("color", CASE "code"
    WHEN 'LEAD' THEN '#607D8B' WHEN 'CONTACTED' THEN '#2196F3'
    WHEN 'INTERESTED' THEN '#00BCD4' WHEN 'QUALIFIED' THEN '#3F51B5'
    WHEN 'NEEDS_ASSESSMENT' THEN '#673AB7' WHEN 'PENDING_PRE_INVOICE_APPROVAL' THEN '#9C27B0'
    WHEN 'POC_PILOT_SCHEDULED' THEN '#FF9800' WHEN 'POC_PILOT_IN_PROGRESS' THEN '#FF5722'
    WHEN 'PENDING_POC_PILOT_APPROVAL' THEN '#795548' WHEN 'PENDING_PAYMENT_INVOICE_APPROVAL' THEN '#CDDC39'
    WHEN 'INSTALLATION_SCHEDULED' THEN '#8BC34A' WHEN 'INSTALLATION_IN_PROGRESS' THEN '#4CAF50'
    WHEN 'PENDING_CUSTOMER_ACCEPTANCE' THEN '#009688' WHEN 'DONE' THEN '#2E7D32'
    WHEN 'ON_HOLD' THEN '#F9A825' WHEN 'LOST' THEN '#C62828' WHEN 'NO_RESPONSE' THEN '#757575'
    ELSE "color"
  END);
