export const NOTIFICATION_EVENT_CATALOG = {
  MEETING: {
    CREATED: "MEETING.CREATED",
    UPDATED: "MEETING.UPDATED",
    CANCELLED: "MEETING.CANCELLED",
  },
  TASK: {
    ASSIGNED: "TASK.ASSIGNED",
    REASSIGNED: "TASK.REASSIGNED",
    COMPLETED: "TASK.COMPLETED",
  },
} as const

export type NotificationEventName =
  | (typeof NOTIFICATION_EVENT_CATALOG.MEETING)[keyof typeof NOTIFICATION_EVENT_CATALOG.MEETING]
  | (typeof NOTIFICATION_EVENT_CATALOG.TASK)[keyof typeof NOTIFICATION_EVENT_CATALOG.TASK]

export const NOTIFICATION_CHANNELS = ["EMAIL", "SMS", "PUSH", "IN_APP"] as const
export type NotificationChannelCode = (typeof NOTIFICATION_CHANNELS)[number]
